### PR TITLE
Update Vignettes

### PR DESCRIPTION
**Pull request by TahminaMojumder**

### CODE REVIEW

**Comment by TahminaMojumder** [comment]
should there be an example for convergence check??

https://github.com/florianhartig/BayesianTools/blob/92b3ca9b3398555bd37125c69264ad8c3f3223cb/BayesianTools/vignettes/BayesianTools.Rmd#L154

There are several places where eval = F - is this intentional?

https://github.com/florianhartig/BayesianTools/blob/92b3ca9b3398555bd37125c69264ad8c3f3223cb/BayesianTools/vignettes/BayesianTools.Rmd#L204

https://github.com/florianhartig/BayesianTools/blob/92b3ca9b3398555bd37125c69264ad8c3f3223cb/BayesianTools/vignettes/BayesianTools.Rmd#L225

https://github.com/florianhartig/BayesianTools/blob/92b3ca9b3398555bd37125c69264ad8c3f3223cb/BayesianTools/vignettes/BayesianTools.Rmd#L237

https://github.com/florianhartig/BayesianTools/blob/92b3ca9b3398555bd37125c69264ad8c3f3223cb/BayesianTools/vignettes/BayesianTools.Rmd#L287

**Comment by florianhartig** [comment]
Hi Tahmina, 

The Gelman Diagnostics are the convergence checks - if you want, you can clarify this in the text.

The eval = F is correct, the code is not supposed to run - if you think that clarifies things for the reader, you could add a comment that this is not excecutable R code, but just pseudocode that shows the principle in which one should program the functions.

**Comment by TahminaMojumder** [comment]
Write here some links that were useful to me to understand MCMC

**Comment by florianhartig** [comment]
Hi @TahminaMojumder , I'm looking at merging this branch, but can you still revert all line breaks that you added? I think this is easier for the future!

**Comment by florianhartig** [comment]
Hi @TahminaMojumder - I think you said you changed back the line breaks, but I still see them - did you commit this?

**Comment by TahminaMojumder** [comment]
For Rmd files, when I changed from source to visual to source again. Then the changes in line break I made changed again to previous version. That is how the changes I made was not committed. Now I have fixed this.

**Pull request merged**
