### PR TITLE
Feature plot diagnostic

### PR DESCRIPTION
**Pull request by MaximilianPi**

### CODE REVIEW

**Comment by TankredO** [comment]
Checks failed:
```
* checking R code for possible problems ... NOTE
plotDiagnostic: no visible global function definition for ‘n2mfrow’
plotDiagnostic: no visible global function definition for ‘?’
plotDiagnostic: no visible binding for global variable ‘ploDICResult’
plotDiagnostic: no visible global function definition for ‘rainbow’
Undefined global functions or variables:
  ? n2mfrow ploDICResult rainbow
Consider adding
  importFrom("grDevices", "n2mfrow", "rainbow")
  importFrom("utils", "?")
to your NAMESPACE file.
* checking Rd files ... WARNING
checkRd: (5) This.Rd:0-44: Must have a \description
```

**Comment by TankredO** [comment]
Description for Roxygen2 documentation missing. You need to add a line with some description above the first "#'@" line. E.g. "#' This function does this and that".

**Comment by TankredO** [comment]
I don't know if this is very important, but to be consistent with the other functions in the package, maybe it might be better to pass "..." to getSample instead of having arguments numSamples and start.

**Comment by MaximilianPi** [comment]
Well I thought about, but I'm already passing different arguments to getSample function directly and over the DIC/WAIC/PSRF functions indirectly so I think that might lead only to confusion

**Comment by TankredO** [comment]
The function arguments need to be in the same order as in the documentation

**Comment by MaximilianPi** [comment]
I will modiy the function so the pull request is on hold

**Pull request merged**
