### PR TITLE
print functions for the most important classes

### PR DESCRIPTION
**Pull request by MaximilianPi**

### CODE REVIEW

**Comment by florianhartig** [comment]
@MaximilianPi - this doesn't' check out yet in Travis

**Comment by TankredO** [comment]
There is still some S3 method problem

**Comment by florianhartig** [comment]
Hey guys, if you implement new things, can you take care that everything new function also gets a unit test right away? (Haven't checked if this is the case now, just a general comment)

**Comment by MaximilianPi** [comment]
I have solved it, there was a mistake in the method specification. I will add a unit test

**Pull request merged**
